### ISSUE TITLE
config for germany

### ISSUE THREAD

**Issue by E3V3A** [fewieden/MMM-OlympicGames#3]
This is very nice. But which config did you use to get Germany to show up?
What if you want to see, lets say top 8 and then 2 additional countries, regardless their position? 
Would that be possible?

**Comment by fewieden** [comment]
I'm sorry the screenshot is from the last olympic summer games in rio, where I used a different data source. The new one only provides 3 letter country codes. I forgot to add a new screenshot, when I was fixing the module at midnight yesterday.

Basically it's not supported to highlight multiple countries. If you want Germany then use `highlight: 'GER'`, if you want another country then you have to specify the official 3 letter country code of that country. It will be in the list no matter if it is in the top 10 or not

**Comment by E3V3A** [comment]
Very nice. Thank you!
